### ISSUE TITLE
Optimize git fetches on worker processes

### ISSUE THREAD

**Issue by krohling** [openfido/openfido#20]
Currently we just do a git clone, and then a switch to the branch.

Instead do a shallow git clone of just the branch we want (ie, clone without copying all the history).

For large git repositories this will speed up the clone operation:

```git clone --depth 1 https://path/to/repo/foo.git -b bar```

**Comment by avpeery** [comment]
Git does not do a depth 1

**Comment by avpeery** [comment]
PRIORITY

**Comment by Thistleman** [comment]
git clone script was updated to only clone the specified branch. Resolved.
